decentraland/nft-server

- entrypoint.sh
- package.json
This PR removes the `npm run start` from the image that contained a build procedure.
> fix: Remove run start

- src/ports/browse/sources/marketplace.spec.ts
- src/ports/browse/sources/marketplace.ts
This PR defines a default value for the estate name when there's no data about it or the name of the estate is null.
> fix: Add fixes to the estate data and name

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/items.ts
- src/adapters/handlers/nfts.ts
- src/ports/items/types.ts
- src/ports/items/utils.ts
- src/ports/nfts/types.ts
- src/ports/nfts/utils.ts
- On the NFT level renamed `wearableRarity` to `itemRarity`, so the wearable only properties are prefixed with `wearable` (like `wearableGender` and `wearableCategory`) and the item only properties are prefixed with `item` (like `itemRarity` and `itemId`).
- On the item level, it is just `rarity` instead of `wearableRarity`
- Fixed bug in item pagination using now `createdAt` to sort results.
- Added `isOnSale` property to items (which is `true` if the store has been added as minter and the max supply has not been reached)
> fix: items

- .ci/index.ts
This PR increases the instances of the service in production from 1 to 3. It also sets the cpuReservation variable to 256, the default value that it had before, but makes it visible.
> chore: Increase instances count

- src/adapters/routes.ts
- src/index.ts
- src/logic/request-logger-middleware.ts
- src/types.ts
Log all incoming requests displaying:
- id: For tracing request and response
- state: State of the request, REQUEST for when the request is received, SUCCESS when there is a successful response, FAILURE for the contrary, UNHANDLED_FAILURE when the request fails without being handled correctly and UNKOWN where there is a response without status code (I have no clue when that could happen but better safe than sorry)
- code: Status code of the response
- time: Time taken between the start of the request and the response
- message: Currently used to display the error of >= 500 responses and UNHANDLED_FAILUREs
```
2021-11-18T17:03:13.083Z [INFO] (nft-server): http://localhost:5000/v1/nfts?foo=bar     {"id":1637254993083,"state":"REQUEST"}
2021-11-18T17:03:14.044Z [INFO] (nft-server): …
```
> feat: Add request logger middleware

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/accounts.ts
- src/adapters/routes.ts
- src/adapters/sources/accounts.ts
- src/index.ts
- src/ports/accounts/component.ts
- src/ports/accounts/types.ts
- src/ports/accounts/utils.ts
- src/types.ts
Add `/accounts` endpoint.
Returns a collection of the `Account` model which currently contains a bunch of metrics about earning and spending.
> feat: Add accounts endpoint

- src/index.ts
- src/ports/sales/component.ts
- src/ports/sales/utils.ts
The Ethereum subgraphs don't have the `SaleType.MINT` so it throws when the query has that value.
> fix: sales type mint

- .ci/index.ts
Fixes:
```
pulumi:pulumi:StackReference (prometheus-dev):
error: resource 'urn:pulumi:nft-server-dev::nft-server::pulumi:pulumi:StackReference::prometheus-dev' registered twice (read and read)
```
causing the pipeline to fail
> fix: prometheus stack registered twice

- src/adapters/sources/rentals.ts
- src/logic/nfts/rentals.ts
- src/ports/nfts/component.ts
- src/ports/nfts/types.ts
- src/ports/nfts/utils.ts
- src/tests/adapters/sources/nft-source.spec.ts
- src/tests/adapters/sources/rentals-source.spec.ts
- src/tests/logic/nft-rentals.spec.ts
- src/tests/ports/nfts.spec.ts
This PR improves the NFT fetching procedure when rentals are requests by using `id_in`.
This PR also fixes the should fetch function of the rentals source to check the `isLand` parameter when there's no category set.
> fix: Improve NFT fetch performance on rentals

- src/ports/rankings/component.ts
- src/ports/rankings/utils.ts
Closes #131
Both by volume and by sales are returning the same values now:
> feat: add recursive fetch to rankings query

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/items.ts
- src/ports/items/utils.ts
- src/ports/trendings/component.ts
- src/tests/ports/trendings.spec.ts
This PR adds support for multiple `contractAddress` params in the `/items` endpoint
Closes #136
> feat: converted single contract address filter into multiple

- src/ports/rentalNFTs/component.ts
- src/ports/rentals/components.ts
This PR fixes the requests that use the `owner` property by querying by lessor when asking for the owners (it was checking for an array with at least two elements) and by not querying for marketplace NFTs when there are no NFTs rented.
> fix: LAND not returning correctly when rented

- src/adapters/sources/rentals.ts
- src/index.ts
- src/ports/merger/component.ts
- src/ports/merger/types.ts
The NFT server was skipping the data that comes from the signature server that only skips results by itself.
This PR removes the need to skip things if they're not needed.
> fix: Don't skip if data comes from the signature server

- src/ports/rentals/components.ts
- src/tests/ports/rentals.spec.ts
This PR changes the order of the NFT requested when requesting for the NFTs that have rentals ordered by max rental price. That is, ordered by the maximum value of their rental prices by day.
As of today, the maximum value of the rental price on all periods is the same as the minimum one, but we're using the maximum value everywhere due to the chance of someone registering the values manually.
> fix: Order max rental price ascending

- src/ports/nfts/utils.ts
Use gte and lte for graphql query so that it also considers valid when the price is equal to the one send in params
> fix: use gte and lte in price filter

- src/adapters/handlers/nfts.ts
- src/logic/nfts/collections.ts
- src/ports/nfts/component.ts
This fixes two things:
- Prevents a query to be made to the graph is the token id is invalid or if the token id is set but there's no contract address for it.
- Prevents a collections query to be performed when requesting rented land with a rental status.
> fix: Throw bad request when no token id is provided

- src/index.ts
This was required until this [issue](https://github.com/decentraland/marketplace/issues/1136) was resolved.
It is not needed anymore.
> feat: Remove alt subgraph

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/items.ts
- src/adapters/handlers/nfts.ts
- src/ports/items/utils.spec.ts
- src/ports/items/utils.ts
- src/ports/nfts/utils.spec.ts
- src/ports/nfts/utils.ts
Change logic to allow multiple play modes and not just one. Playmode is now being saved in the graph as a boolean (`loop`) but the idea is that in the future there will be more playmodes. So the logic is:
- `?emotePlayMode=simple` searches all items with `loop=false` in the graph
- `?emotePlayMode=loop` searches all items with `loop=true` in the graph
- `?emotePlayMode=loop&emotePlayMode=simple` will bring all `loop=true` and `loop=false` (the same as is the filter is not sent
> feat: add ability to filter by multiple play modes

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/items.ts
- src/adapters/handlers/nfts.ts
- src/ports/items/utils.spec.ts
- src/ports/items/utils.ts
- src/ports/nfts/utils.spec.ts
- src/ports/nfts/utils.ts
- src/ports/utils.ts
Add unisex option to body shape filter. The options are:
- male (will bring all items|nfts that only have male as a bodyShape)
- female (will bring all items|nfts that only have female as a bodyShape)
- male_female (will bring all items|nfts that have male and female as a bodyShape)
- unisex (will bring all items|nfts that have male and female as a bodyShape)
- male_unisex (will bring all items|nfts that have male as a bodyShape. including the ones that have also female)
- female_unisex (will bring all items|nfts that have female as a bodyShape. including the ones that have also male)
> feat: add unisex option to body filter

- src/ports/nfts/utils.spec.ts
- src/ports/nfts/utils.ts
When filtering only by parcels or estates the isLand boolean is not being send as part of the filters, so this pr adds category condition so `adjacentToRoad` `minDistanceToPlaza` and `maxDistanceToPlaza` will work in those cases
> fix: remove is land condition for distance to plaza

- src/ports/rankings/utils.ts
> fix: use "gte" operator to include rankings min date in the calculation

- package-lock.json
- package.json
This PR updates the http requests logger component so it doesn't log the `ready` requests.
> fix: Update the http requests logger component

- src/ports/favorites/components.ts
- src/ports/rentals/components.ts
- src/ports/utils.ts
- src/tests/ports/rentals.spec.ts
- src/tests/ports/utils.spec.ts
> refactor: New util to fetch same url multiple times to avoid exceeding the max length with one query parameter

- package-lock.json
- package.json
- src/index.ts
- src/logic/nfts/collections.ts
- src/logic/nfts/marketplace.ts
- src/ports/orders/component.ts
- src/ports/orders/types.ts
- src/ports/orders/utils.ts
- src/tests/components.ts
missing update for common schemas
> feat: add issuedId to orders

- src/adapters/handlers/utils.ts
- src/ports/catalog/queries.ts
- src/ports/catalog/utils.ts
- src/tests/adapters/handlers/utils.spec.ts
- src/tests/ports/catalog-queries.spec.ts
This PR address the following things:
- The `owners_count` field was getting calculated on the JOIN with the opened orders, so it wasn't accurate. Now it's getting computed on all the NFTs joined with the items.
- Fixes the `getIsOnSale` condition: now it also has the logic for "not on sale", when there are no listings and it's either not on sale or sold out.
- For `recently_listed`, updates the logic and sorts by the greateast between `max_order_created_at` and `first_listed_at`, using the newest field to sort.
- For `chepeast`, updates the logic and sorts by `first_listed_at` as secondary field
> fix: fix unified markets query to include proper owner count

- src/ports/catalog/queries.ts
All subgraphs are indexing the new field `item` in the order entity so we avoid the NFT JOIN when getting the listings.
> feat: catalog: avoid joining the NFT table so it goes faster

- src/ports/catalog/queries.ts
- src/tests/ports/catalog-queries.spec.ts
`search_is_store_minter` needs to be `true` for the item to be on sale, it was missing in the `WHERE` statement when applying a min price.
> fix: minPrice query price missing if the item is on sale

- src/ports/catalog/queries.ts
- src/tests/ports/catalog-queries.spec.ts
The frontend needs to know about the listings in the range if it's applied. Adding the `WHERE` conditions in the orders JOIN will do the job.
> feat: add price range to the Orders JOIN to filter listings in that range

- src/ports/catalog/queries.ts
- src/tests/ports/catalog-queries.spec.ts
This PR adds the price filter in the `min_price` and `max_price` `CASE` statements where they are defined. This is needed so they are sorted in the correct order at the end of the query.
> fix: add MIN and MAX price filters in CASE for min_price and max_price

- src/ports/owner/utils.ts
the index is created on `left(contract_address, 256)`. Most probably to save disk space, so we need to explicity filter against it.
> fix: owners query not using the right index for contract_address

- src/ports/catalog/component.ts
The `client.release()` removed in this PR is unnecessary since it's executed in the `finally` [here](https://github.com/decentraland/nft-server/pull/306/files#diff-266d78ef6bf1741665662502c979d2ad238b72aca682e549cdb2402950c1a813L105)
> fix: remove unnecessary client.release()

- .env.spec
- src/adapters/sources/items.ts
- src/index.ts
- src/ports/catalog/component.ts
- src/tests/adapters/sources/item-source.spec.ts
- src/tests/components.ts
- src/tests/ports/catalog.spec.ts
This PR removes the Favorites Feature flag which is no longer used.
> fix: Remove Favorites FF

- src/index.ts
- src/logic/prices/marketplace.ts
- src/ports/prices/component.ts
- src/tests/components.ts
- src/tests/ports/prices.spec.ts
Marketplace graph doesn't have this new category as it will only be included in new wearables (that are in the collections graph). This pr adds a new validation for the priceComponent for marketplace graph so that it doesn't fetch if the wearableCategory filter is `hands_wear`
> fix: prices fetch with wearablecategory hands

- src/index.ts
- src/logic/nfts/marketplace.ts
- src/ports/nfts/component.ts
Fix error when fetching nfts with category hands. It should not fetch marketplace graph as the category doesn't exist in old wearables
> fix: do not call marketplace graph when category hands

- src/logic/expiration.ts
- src/logic/nfts/collections.ts
- src/logic/nfts/marketplace.spec.ts
- src/ports/orders/utils.ts
The expiration of orders were computed in milliseconds instead of seconds. This PR changes it so orders don't get expired.
> fix: Expiration of orders in seconds

- src/ports/catalog/component.ts
- src/ports/catalog/queries.ts
- src/ports/nfts/component.ts
- src/ports/nfts/utils.ts
- src/subgraphUtils.ts
- src/tests/ports/catalog-queries.spec.ts
- src/tests/ports/catalog.spec.ts
> feat: fuzzy search implementation

- src/adapters/handlers/catalog.ts
- src/ports/catalog/component.ts
- src/ports/catalog/queries.ts
- src/ports/catalog/utils.ts
- src/tests/ports/catalog.spec.ts
The main query should have the `filter.search` param cleaned so it doesn't sort by relevance. (It will sort by relevance if no other sort is used).
> fix: main catalog query sort when filtering by text

- src/ports/catalog/component.ts
- src/ports/catalog/queries.ts
- src/tests/ports/catalog-queries.spec.ts
- src/tests/ports/catalog.spec.ts
The query was missing the LIMIT & OFFSET parameters so it might have been bringing a lot of results and using a lot of memory.
> feat: add limit & offset to the catalog search pre-query

- src/logic/nfts/marketplace.spec.ts
- src/ports/catalog/queries.ts
- src/tests/ports/catalog-queries.spec.ts
- src/tests/ports/catalog.spec.ts
When searching for items in the catalog by a search term we should not limit the query that search for ids with specific term as it will cause for some items to be filtered before doing the proper catalog search
before this change
`/v1/catalog?first=5&category=wearable&search=m` would return only one item as it will only consider the first 5 ids that match the term m to later do the wearable category filter
after this change
`/v1/catalog?first=5&category=wearable&search=m` will return 5 (with the total being 81)
> fix: catalog search ignore limit and offset

- .github/workflows/test.yml
- Dockerfile
- package-lock.json
- package.json
- src/adapters/handlers/utils.ts
- src/logic/contracts.ts
- src/ports/bids/component.ts
- src/ports/bids/utils.ts
- src/ports/catalog/component.ts
- src/ports/catalog/types.ts
- src/ports/catalog/utils.ts
- src/ports/collections/component.ts
- src/ports/collections/utils.ts
- src/ports/items/component.ts
- src/ports/items/utils.ts
- src/ports/mints/component.ts
- src/ports/mints/utils.ts
- src/ports/orders/component.ts
- src/ports/orders/utils.ts
- src/ports/sales/component.ts
- src/ports/sales/utils.ts
- src/tests/ports/catalog.spec.ts
- src/tests/ports/trendings.spec.ts
- src/types.ts
This PR changes the NFT server to support the exotic rarity.
> feat: Support Exotic rarity

- .env.defaults
- src/index.ts
This PR makes the CORS environment variable work with regular expressions.
> feat: Make CORS origin work with regex

- .env.defaults
- .env.spec
- package-lock.json
- package.json
- src/index.ts
- src/ports/builder/component.ts
- src/ports/builder/index.ts
- src/ports/builder/types.ts
- src/ports/items/component.ts
- src/ports/items/index.ts
- src/ports/nfts/component.ts
- src/tests/components.ts
- src/tests/ports/builder.spec.ts
- src/tests/ports/items.spec.ts
- src/tests/ports/nfts.spec.ts
- src/types.ts
This PR modifies the NFT server so when an item or an nft is fetched as a single asset, the utility is fetched from the builder-server.
> feat: Fetch and add the utility property

- src/adapters/handlers/orders.ts
This PR changes the NFT-server to correctly respond to an invalid item id. Item ids are numeric. All of them should fall in the Number region, but just in case, it is parsed as BigInt.
> fix: Correctly respond to an invalid item id
