- README.md
- package-lock.json
- package.json
- src/adapters/sources/items.ts
- src/index.ts
- src/ports/items/types.ts
- src/ports/items/utils.ts
This PR adds a new way to sort items by `recently_reviewed`
> feat: sort by recently_reviewed

- src/ports/subgraph/component.ts
> feat: handle http error

- package-lock.json
- package.json
- src/adapters/handlers/collections.ts
- src/ports/collections/utils.ts
Search collections by providing the `name` query param
> feat: Filter collections by name

- src/logic/request-logger-middleware.ts
Logging when the request is received does not provide any useful information
Added request method to log
Moved query into the data json so it is not so cumbersome
> feat: Improve request logger middleware

- src/ports/items/types.ts
- src/ports/items/utils.ts
This PR gets the body shapes from the metadata instead of the search text.
> chore: Get wearables body shapes from metadata

- src/ports/items/types.ts
- src/ports/items/utils.ts
Reverts decentraland/nft-server#35
Closes #37
> Revert "chore: Get wearables body shapes from metadata"

- src/ports/items/utils.ts
fix: show items with price=0 as not on sale
> fix: show items with price=0 as not on sale

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/items.ts
- src/ports/items/types.ts
- src/ports/items/utils.ts
This PR adds support for the filter `itemType` to filter items whether they are smart wearables or not. Also adds the `Item.type` property to results.
> feat: added support for itemType filter and Item.type property

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/items.ts
- src/adapters/handlers/nfts.ts
- src/logic/nfts/collections.ts
- src/logic/nfts/marketplace.ts
- src/ports/items/types.ts
- src/ports/items/utils.ts
fix: use isWearableSmart instead of itemType and upgrade common-schemas
> fix: use isWearableSmart instead of itemType and upgrade common-schemas

- README.md
- package-lock.json
- package.json
- src/ports/accounts/component.ts
- src/ports/items/component.ts
Added `skin` category and fixed an issue when querying `/items?network=ETHEREUM` it should return `[]` and it was ignoring it.
> feat: added skin category

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/items.ts
- src/adapters/handlers/nfts.ts
- src/logic/nfts/collections.spec.ts
- src/logic/nfts/collections.ts
- src/logic/nfts/marketplace.ts
- src/ports/items/types.ts
- src/ports/items/utils.ts
- src/ports/nfts/utils.ts
Added support for items and nfts of type `emote` and filters.
> feat: emotes

- src/ports/items/utils.ts
> feat: stop filtering 0-priced items

- .ci/index.ts
- package-lock.json
- package.json
- src/ports/items/utils.ts
Min sale value as an ENV variable:
`MIN_SALE_VALUE_IN_WEI`
> fix: min sale value as an env var

- src/index.ts
- src/ports/sales/utils.ts
- src/ports/trendings/component.ts
- src/ports/trendings/types.ts
- src/ports/trendings/utils.ts
- src/tests/components.ts
- src/tests/ports/trendings.spec.ts
> fix: Loop until all sales from timeframe are retrieved

- .ci/index.ts
- README.md
- package-lock.json
- package.json
- src/adapters/handlers/sales.ts
- src/index.ts
- src/ports/sales/utils.ts
DO NOT MERGE - Needs to update dcl schemas first
> feat: add the searchCategory where filter for sales

- src/ports/rankings/utils.ts
> feat: Query creators by primary sales and primary sale earns

- .ci/index.ts
Testing if this changes fixes the pulumi error that we're getting
> feat: change TTL values for /trendings PageRule

- package-lock.json
- package.json
- src/adapters/sources/nfts.ts
- src/adapters/sources/rentals.ts
- src/index.ts
- src/logic/nfts/collections.spec.ts
- src/logic/nfts/collections.ts
- src/logic/nfts/marketplace.ts
- src/tests/adapters/sources/nft-source.spec.ts
- src/tests/adapters/sources/rentals-source.spec.ts
This PR adds the open rental id property in the NFT type.
> feat: Add open rental id

- src/ports/items/utils.ts
- src/ports/nfts/utils.ts
- src/tests/ports/nfts.spec.ts
This PR allows filter emotes by rarities
> fix: Filter emotes by rarities

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/items.ts
- src/adapters/handlers/nfts.ts
- src/logic/nfts/collections.spec.ts
- src/logic/nfts/collections.ts
- src/ports/items/types.ts
- src/ports/items/utils.ts
- src/ports/nfts/utils.ts
- src/tests/ports/nfts.spec.ts
This PR allows filter emotes in the subgraph by field `searchEmoteLoop`.
depends on https://github.com/decentraland/common-schemas/pull/133
> feat: Filter emotes by play mode

- src/ports/items/utils.ts
The if was always passing and the query ended up with an empty array, that returned no results 🤦‍♂️ .
> fix: check length of array before adding to the query

- src/logic/contracts.ts
This PR adds the category: `WEARABLE | EMOTE` to the collections, if contains wearables or emotes items.
This allows filter properly by collections in the marketplace.
> feat: Add emote or wearable category to the contracts

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/nfts.ts
- src/ports/nfts/utils.ts
Add two new possible query params in nfts request.
- `minPrice`
- `maxPrice`
Closes #83
> feat: add filter by price in NFTs

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/items.ts
- src/ports/items/utils.spec.ts
- src/ports/items/utils.ts
Add minPrice and maxPrice filter to items
> feat: add price filter items

- package-lock.json
- package.json
- src/adapters/handlers/items.ts
- src/adapters/handlers/nfts.ts
- src/ports/items/utils.spec.ts
- src/ports/items/utils.ts
- src/ports/nfts/utils.ts
- src/ports/rentals/components.ts
Send min price and max price to signature server for rentals
> feat: add min price and max price to rentals

- src/adapters/handlers/prices.ts
- src/logic/prices/collections.ts
- src/logic/prices/marketplace.ts
- src/ports/nfts/utils.ts
- src/ports/prices/component.ts
- src/ports/prices/types.ts
> feat: add some NFTFilters filters to the Price endpoint

- src/logic/prices/collections.ts
- src/logic/prices/marketplace.ts
- src/tests/logic/prices-utils.spec.ts
> fix: fix wearableSmart and collection filters for /prices endpoint

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/items.ts
- src/ports/items/utils.spec.ts
- src/ports/items/utils.ts
> feat: Allow filtering items by urns

- package-lock.json
- package.json
- src/adapters/sources/collections.ts
- src/adapters/sources/items.ts
- src/index.ts
- src/ports/collections/types.ts
- src/ports/collections/utils.spec.ts
- src/ports/collections/utils.ts
- src/ports/items/types.ts
- src/ports/items/utils.spec.ts
- src/ports/items/utils.ts
- src/tests/components.ts
- src/tests/ports/trendings.spec.ts
> feat(First Listed At): Support sorting by firstListedAt

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/nfts.ts
- src/adapters/handlers/stats.ts
- src/adapters/routes.ts
- src/index.ts
- src/logic/nfts/collections.ts
- src/ports/nfts/utils.ts
- src/ports/stats/component.ts
- src/ports/stats/types.ts
- src/ports/stats/utils.ts
- src/tests/components.ts
- src/tests/ports/stats.spec.ts
- src/types.ts
> feat: Add new endpoint for estates size stat

- src/ports/nfts/utils.ts
handle 0 case on maxDistanceToPlaza
> fix: distance to plaza 0

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/accounts.ts
- src/adapters/handlers/items.ts
- src/adapters/handlers/nfts.ts
- src/adapters/sources/accounts.ts
- src/index.ts
- src/logic/accounts/collections.ts
- src/logic/accounts/marketplace.ts
- src/logic/http/params.ts
- src/logic/nfts/collections.ts
- src/ports/accounts/component.ts
- src/ports/accounts/types.ts
- src/ports/accounts/utils.ts
- src/ports/items/utils.ts
- src/tests/components.ts
> feat: add support for creator on nfts and item endpoint and add support for address array in /accounts

- README.md
- src/adapters/handlers/prices.ts
- src/adapters/handlers/stats.ts
- src/logic/prices/marketplace.ts
- src/ports/nfts/utils.ts
- src/ports/prices/types.ts
- src/ports/stats/component.ts
- src/ports/stats/types.ts
- src/ports/stats/utils.ts
- src/tests/ports/stats.spec.ts
> feat: read land filters on stats and prices endpoints

- package-lock.json
- package.json
- src/index.ts
This PR updates the http-requests-logger component to its latest version.
> fix: Update request logger to its latest version

- src/adapters/handlers/owners.ts
- src/adapters/routes.ts
- src/index.ts
- src/ports/owner/component.ts
- src/ports/owner/types.ts
- src/ports/owner/utils.spec.ts
- src/ports/owner/utils.ts
- src/tests/components.ts
- src/tests/ports/owners.spec.ts
- src/types.ts
> feat: owners endpoint

- package-lock.json
- package.json
- src/adapters/handlers/orders.ts
- src/adapters/sources/orders.ts
- src/index.ts
- src/ports/orders/component.ts
- src/ports/orders/utils.ts
- src/tests/components.ts
> feat: modifications to order endpoint to filter by itemId and sort by issue id and oldest

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/items.ts
- src/ports/items/utils.spec.ts
- src/ports/items/utils.ts
Closes #259 
Wait for https://github.com/decentraland/schemas/pull/181 and bump de common schemas before merging this PR.
> feat: Allow filtering items by multiple ids

- .env.spec
- package-lock.json
- package.json
- src/adapters/handlers/items.ts
- src/adapters/routes.ts
- src/adapters/sources/items.ts
- src/index.ts
- src/logic/items/utils.ts
- src/ports/favorites/components.ts
- src/ports/favorites/types.ts
- src/ports/items/types.ts
- src/ports/rentals/components.ts
- src/ports/rentals/types.ts
- src/ports/utils.ts
- src/tests/adapters/sources/item-source.spec.ts
- src/tests/components.ts
- src/tests/logic/item-utils.spec.ts
- src/tests/ports/favorites.spec.ts
- src/types.ts
- src/types/server.ts
> feat: Augment items with favorites data

- README.md
- package-lock.json
- package.json
- src/adapters/handlers/items.ts
- src/adapters/handlers/utils.ts
- src/ports/catalog/component.ts
- src/ports/catalog/queries.ts
- src/ports/catalog/types.ts
- src/ports/catalog/utils.ts
- src/tests/adapters/handlers/utils.spec.ts
> feat: add support by Ids to the /catalog endpoint

- src/ports/catalog/queries.ts
- src/tests/ports/catalog-queries.spec.ts
`listings_count` should be > 0
> fix: catalog only listing query filter

- src/index.ts
- src/logic/db/connection.ts
- src/ports/owner/component.ts
- src/ports/owner/types.ts
- src/ports/owner/utils.spec.ts
- src/ports/owner/utils.ts
- src/tests/components.ts
- src/tests/ports/owners.spec.ts
> feat: use the database component to fetch owners

- src/ports/catalog/component.ts
- src/tests/ports/catalog.spec.ts
If the first search query doesn't return any matches, we need to return an empty array and avoid calling the main catalog query.
> fix: catalog query search empty matches

- README.md
- package-lock.json
- package.json
Bump common schemas to last version to allow new hands_wear in nft server
Closes https://github.com/decentraland/nft-server/issues/315
> feat: bump common schemas

- package-lock.json
- package.json
- src/logic/nfts/collections.spec.ts
- src/logic/nfts/collections.ts
- src/ports/catalog/queries.ts
- src/ports/catalog/types.ts
- src/ports/catalog/utils.ts
- src/ports/items/types.ts
- src/ports/items/utils.spec.ts
- src/ports/items/utils.ts
- src/tests/ports/catalog.spec.ts
- src/tests/ports/nfts.spec.ts
- src/tests/ports/trendings.spec.ts
This PR adds the `urn` field to `Wearables` and `Emotes`.
Closes #317
> feat: Add urn field to Wearables and Emotes

- src/index.ts
- src/ports/collections/utils.ts
- src/ports/sales/component.ts
- src/ports/sales/utils.ts
- src/tests/ports/sales.spec.ts
> fix: fix the sales endpoint for L1 collections

- src/logic/nfts/collections.ts
This PR fixes missing urn property for items NFT payload
> fix: Add missing urn property for items payload

- package-lock.json
- package.json
- src/ports/catalog/queries.ts
- src/tests/ports/catalog-queries.spec.ts
This PR adds the Catalog URN filter to get items by their URN.
> feat: Add Catalog URN filter

- src/ports/catalog/component.ts
- src/ports/catalog/utils.ts
- src/tests/ports/catalog-utils.spec.ts
> fix: creators var will always have value and fallbacks network to Matic

- src/ports/catalog/component.ts
This PR fixes the search by text when looking at multiple networks
> fix: Search by text

- package-lock.json
- package.json
- src/adapters/handlers/utils.ts
- src/logic/nfts/collections.spec.ts
- src/logic/nfts/collections.ts
- src/ports/catalog/queries.ts
- src/ports/catalog/types.ts
- src/ports/catalog/utils.ts
- src/ports/items/types.ts
- src/ports/items/utils.spec.ts
- src/ports/items/utils.ts
- src/tests/adapters/handlers/utils.spec.ts
- src/tests/ports/catalog-queries.spec.ts
- src/tests/ports/catalog.spec.ts
- src/tests/ports/nfts.spec.ts
This reverts commit a4b68de19faa121257f9ac26e08a61e0217f4801.
> Revert "feat: add emoteHasSound and emoteHasGeometry filters (#343)"

- package-lock.json
- package.json
- src/adapters/handlers/utils.ts
- src/logic/nfts/collections.spec.ts
- src/logic/nfts/collections.ts
- src/ports/catalog/queries.ts
- src/ports/catalog/types.ts
- src/ports/catalog/utils.ts
- src/ports/items/types.ts
- src/ports/items/utils.spec.ts
- src/ports/items/utils.ts
- src/tests/adapters/handlers/utils.spec.ts
- src/tests/ports/catalog-queries.spec.ts
- src/tests/ports/catalog.spec.ts
- src/tests/ports/nfts.spec.ts
Reverts decentraland/nft-server#345
> Revert "Revert "feat: add emoteHasSound and emoteHasGeometry filters (#343)""

- package-lock.json
- package.json
- src/adapters/handlers/prices.ts
- src/ports/nfts/utils.spec.ts
- src/ports/nfts/utils.ts
- src/ports/prices/types.ts
Add logic for prices endpoitn for emoteHasSound and emoteHasGeometry filters
> feat: add logic for emotes 2.0 for prices endpoint

- src/index.ts
Adds a missing file in the latest PR #351
> fix: adds db to the nft component

- Dockerfile
This reverts commit 981281b1a3f7fb14cf7d708a90ed084ca6b99a46.
> fix: Revert "fix: ulimit (#361)"

- src/subgraphUtils.ts
This PR updates the subgraph used in dev from `collections-matic-mumbai` to `collections-matic-amoy`
> feat: Update subgraph used for collections in dev

- src/subgraphUtils.ts
Reverts decentraland/nft-server#370
> Revert "feat: Update subgraph used for collections in dev"
